export const validationRules ={
    ORGANIZATION_NAME_MAX_LENGTH: 30,
    SCHOOL_NAME_MAX_LENGTH: 120,
    PROGRAM_NAME_MAX_LENGTH: 30,
    
    ORGANIZATION_NAME_MIN_LENGTH: 3,
    SCHOOL_NAME_MIN_LENGTH: 3,
    PROGRAM_NAME_MIN_LENGTH: 3
} 