export const validationRules = {
  ORGANIZATION_NAME_MAX_LENGTH: 30,
  SCHOOL_NAME_MAX_LENGTH: 120,
  PROGRAM_NAME_MAX_LENGTH: 30,

  ORGANIZATION_NAME_MIN_LENGTH: 3,
  SCHOOL_NAME_MIN_LENGTH: 3,
  PROGRAM_NAME_MIN_LENGTH: 3,

  CLASS_NAME_MAX_LENGTH: 45,
  CLASS_NAME_MIN_LENGTH: 3,

  SHORT_CODE_MAX_LENGTH: 16,

  CLIENT_MAX_LENGTH: 255,
  STATUS_MAX_LENGTH: 255,

  USER_GIVEN_NAME_MAX_LENGTH: 35,
  USER_FAMILY_NAME_MAX_LENGTH: 35,
  EMAIL_MAX_LENGTH: 250,
  ROLE_NAME_MAX_LENGTH: 20,
  SHORTCODE_MAX_LENGTH: 16,
  GENDER_MIN_LENGTH: 3,
  GENDER_MAX_LENGTH: 16,
  USERNAME_MAX_LENGTH: 50,
};
